export const CREATE_ENTRY_REQUEST = 'CREATE_ENTRY_REQUEST';
export const VALIDATE_ENTRY_SUCCESS = 'VALIDATE_ENTRY_SUCCESS';
export const VALIDATE_ENTRY_FAIL = 'VALIDATE_ENTRY_FAIL';
export const DELETE_ENTRY_REQUEST = 'DELETE_ENTRY_REQUEST';
export const ENTRY_EXIST = 'ENTRY_EXIST';
export const ENTRY_DOES_NOT_EXIST = 'ENTRY_DOES_NOT_EXIST';